# 港口 - 水域中心坐标
ports:
  - {id: 0, name: "Port_A", x: 800, y: 1990}
  - {id: 1, name: "Port_B", x: 1200, y: 2500}
  - {id: 2, name: "Port_C", x: 2000, y: 2640}
  - {id: 3, name: "Port_D", x: 2500, y: 2580}
  - {id: 4, name: "Port_E", x: 3000, y: 2670}
  - {id: 5, name: "Port_F", x: 3800, y: 2780}
  - {id: 6, name: "Port_G", x: 4000, y: 2740}
  - {id: 7, name: "Port_H", x: 4500, y: 2120}
  - {id: 8, name: "Port_I", x: 5000, y: 1790}
  - {id: 9, name: "Port_J", x: 5500, y: 1770}
  - {id: 10, name: "Port_K", x: 6000, y: 1980}
  - {id: 11, name: "Port_L", x: 6200, y: 2070}
  - {id: 12, name: "Port_M", x: 6800, y: 1990}
  - {id: 13, name: "Port_N", x: 7200, y: 1580}
  - {id: 14, name: "Port_O", x: 7400, y: 1460}
  - {id: 15, name: "Port_P", x: 7600, y: 1290}
