# 船舶 — binary_map_scaled.png 像素坐标
ships:
  - id: 0
    name: "Ship_0"
    max_payload: 2000.0
    max_energy: 500.0
    max_speed: 8.0
    start_x: 500
    start_y: 200
    energy_per_km: 2.5
  - id: 1
    name: "Ship_1"
    max_payload: 1500.0
    max_energy: 400.0
    max_speed: 7.5
    start_x: 3700
    start_y: 1050
    energy_per_km: 2.2
  - id: 2
    name: "Ship_2"
    max_payload: 2500.0
    max_energy: 600.0
    max_speed: 7.0
    start_x: 3800
    start_y: 1100
    energy_per_km: 3.0
  - id: 3
    name: "Ship_3"
    max_payload: 1800.0
    max_energy: 450.0
    max_speed: 8.5
    start_x: 2000
    start_y: 500
    energy_per_km: 2.8
